### ISSUE TITLE
issue using external links to groups/datasets

### ISSUE THREAD

**Issue by TheGrim1** [nexpy/nexusformat#51]
I have believe there is a bug in external links to data in nexusformat. See this example:

import nexusformat.nexus as nx

# This is my datafile and the dataset:
testfname = '/data/id13/inhouse6/THEDATA_I6_1/d_2016-11-17_inh_ihsc1404/DATA/AUTO-TRANSFER/eiger1/AJ2c_after_133_master.h5'
testf = nx.nxload(testfname)
testf['entry/data'].keys()
> Out: [u'data_000001']

# I want a file that links to it:
linkfname = '/data/id13/inhouse2/AJ/skript/xsocs/my_example/test.h5'
linkf = nx.nxload(linkfname,'w')
linkf['external_link_test'] = nx.NXlink('/entry/data/', file = testfname)

linkf['external_link_test']
> Out: NXlink(target='/entry/data/', file='/data/id13/inhouse6/THEDATA_I6_1/d_2016-11-17_inh_ihsc1404/DATA/AUTO-TRANSFER/eiger1/AJ2c_after_133_master.h5')

linkf['external_link_test'].keys()
> Out: [u'data_000001']

# looks good but there is no data there:

testf['entry/data']['data_000001'].shape
> Out: (1701, 2167, 2070)

linkf['external_link_test']['data_000001'].shape
> Out: ()

# The original field was already a link:
type(linkf['external_link_test']['data_000001'])
> Out: nexusformat.nexus.tree.NXlinkfield

type(testf['entry/data']['data_000001'])
> Out: nexusformat.nexus.tree.NXlinkfield

# and
linkf['external_link_test']['data_000001']
> Out: NXlink(target='/entry/data/data', file='AJ2c_after_133_data_000001.h5')

testf['entry/data']['data_000001']
> Out: NXlink(target='/entry/data/data', file='AJ2c_after_133_data_000001.h5')

# however:
linkf['external_link_test']['data_000001'].nxfile
> Out: IOError: Unable to open file (unable to open file: name = '/data/id13/inhouse2/AJ/skript/xsocs/my_example/AJ2c_after_133_data_000001.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

# The following works, but that is not how I would like to use the links, as it can only follow through 1 layer of links:
linkf['external_link_test'].nxfile.get('/entry/data/data_000001')
> Out: <HDF5 dataset "data": shape (1701, 2167, 2070), type "<u4">

# I believe this is a bug in nexusformat because h5py has no problem following these links:
import h5py as h5
linkfname='/data/id13/inhouse2/AJ/skript/xsocs/my_example/test.h5'
h5linkf = h5.File(linkfname)
h5linkf.keys()
> Out: [u'external_link_test']

h5link2f['external_link_test'].keys()
> Out: [u'data_000001']

h5link2f['external_link_test/data_000001']
> Out: <HDF5 dataset "data": shape (1701, 2167, 2070), type "<u4">

**Comment by rayosborn** [comment]
Could you tell me what version you are running?
```
import nexusformat
nexusformat.__version__
```
In my attempt to reproduce this, it worked when I did the equivalent of the above, but not when I created the link before saving the file, i.e., opening the test file with nxload in write mode, as you did, worked for me. So I think there is a bug, but I'm not sure it explains what you saw.

**Comment by rayosborn** [comment]
Here is my attempt to reproduce your result.
```
>>> from nexusformat.nexus import *
>>> mf=nxload('/Users/rosborn/Desktop/inhouse6/eiger1/master_file.nxs', 'w')
>>> mf['entry']=NXentry()
>>> mf['entry/data']=NXdata(NXfield(shape=(100,200,300), dtype=np.float32, name='data_0001'))
>>> print(mf.tree)
root:NXroot
  entry:NXentry
    data:NXdata
      @signal = 'data_0001'
      data_0001 = float32(100x200x300)
>>> tf=nxload('/Users/rosborn/Desktop/inhouse2/AJ/test_file.nxs', 'w')
>>> tf['ext_link']=NXlink('/entry/data', file='/Users/rosborn/Desktop/inhouse6/eiger1/master_file.nxs')
>>> print(tf.tree)
root:NXroot
  ext_link:NXdata -> /Users/rosborn/Desktop/inhouse6/eiger1/master_file.nxs['/entry/data']
    @signal = 'data_0001'
    data_0001 = float32(100x200x300)
>>> tf['ext_link/data_0001'].shape
(100, 200, 300)
```
If this is not equivalent to what you were doing, please show me why. In the meantime, I will look into the other bug I came across in investigating this issue.

**Comment by TheGrim1** [comment]
Hello Ray,

thanks for having a look. I used pip to update to nexpy an h5py:
nexusformat.__version__
> u'0.4.14'

h5py.version.version
> '2.7.1'
I can reproduce your example, which honestly surprised me. Then I went back
to see the exact situation that creates an error. It is a link to a goup
containing links in a different path:

# original data:

mf1=nxload('/data/id13/inhouse2/AJ/skript/xsocs/my_example/test1.h5', 'w')
mf1['entry']=NXentry()
mf1['entry/data']=NXdata(NXfield(shape=(100,200,300), dtype=np.float32,
name='data_0001'))
mf2=nxload('/data/id13/inhouse2/AJ/skript/xsocs/my_example/test2.h5', 'w')
mf2['entry']=NXentry()
mf2['entry/data']=NXdata(NXfield(shape=(100,200,300), dtype=np.float32,
name='data'))
print(mf1.tree)
> root:NXroot
>   entry:NXentry
>     data:NXdata
>       @signal = 'data'
>       data = float32(100x200x300)

print(mf2.tree)
> root:NXroot
>   entry:NXentry
>     data:NXdata
>       @signal = 'data'
>       data = float32(100x200x300)

# first link to group data (works):

link1f=nxload('/data/id13/inhouse2/AJ/skript/xsocs/my_example/link1.h5',
'w')
link1f['entry']=NXentry()
link1f['entry/data']=NXdata(name='data')
link1f['entry/data/data_0001']=NXlink('entry/data/data',file='/data/id13/inhouse2/AJ/skript/xsocs/my_example/test1.h5')
link1f['entry/data/data_0002']=NXlink('entry/data/data',file='/data/id13/inhouse2/AJ/skript/xsocs/my_example/test2.h5')
print(link1f.tree)
> root:NXroot
>   entry:NXentry
>     data:NXdata
>       data_0001 ->
/data/id13/inhouse2/AJ/skript/xsocs/my_example/test1.h5['entry/data/data']
>       data_0002 ->
/data/id13/inhouse2/AJ/skript/xsocs/my_example/test2.h5['entry/data/data']

link1f['entry/data/data_0001'].shape
> (100, 200, 300)

# second (broken) link to grouped data links, not the extro subfolder
"folder2":

link2f=nxload('/data/id13/inhouse2/AJ/skript/xsocs/my_example/folder2/link2.h5',
'w')
link2f['ext_link']=NXlink('/entry/data',
file='/data/id13/inhouse2/AJ/skript/xsocs/my_example/link1.h5')
print(linf2f.tree)
> root:NXroot
>   ext_link:NXdata ->
/data/id13/inhouse2/AJ/skript/xsocs/my_example/link1.h5['/entry/data']
>     data_0001 -> test1.h5['entry/data/data']
>     data_0002 -> test2.h5['entry/data/data']

link2f['ext_link/data_0001'].shape
> ()

#While h5py can access this linked data correctrly:
h5link2f =
h5py.File('/data/id13/inhouse2/AJ/skript/xsocs/my_example/folder2/link2.h5')
h5link2f['ext_link/data_0001'].shape
> (100, 200, 300)

# I am quite sure it is a problem with following relative paths. The
following DOES work (no subfolder):

link3f=nxload('/data/id13/inhouse2/AJ/skript/xsocs/my_example/link3.h5',
'w')
link3f['ext_link']=NXlink('/entry/data',
file='/data/id13/inhouse2/AJ/skript/xsocs/my_example/link1.h5')
print(link3f.tree)
> root:NXroot
>   ext_link:NXdata ->
/data/id13/inhouse2/AJ/skript/xsocs/my_example/link1.h5['/entry/data']
>     data_0001 -> test1.h5['entry/data/data']
>     data_0002 -> test2.h5['entry/data/data']

link3f['ext_link/data_0001'].shape
> (100, 200, 300)


hope this is clear.

2018-01-17 19:09 GMT+01:00 Ray Osborn <notifications@github.com>:

**Comment by rayosborn** [comment]
It will take me a little while to unravel all the details in your examples. However, I will point out that `nexusformat` by default makes the links relative, when it saves the file. This is because a common use case is for the links to be to big raw data files stored, say, in the same directory or a sub-directory. The links will be preserved if that directory tree is transferred to another location. However, there is an `abspath` keyword that you can set to true when creating the link. This will ensure absolute file paths are stored. 
```
>>> tf['ext_link']=NXlink('/entry/data', file='/some/absolute/file/path/master_file.nxs', abspath=True)
```
If that helps your problem, please let me know.

**Comment by rayosborn** [comment]
I've made some progress in fixing this. It arises if you create a file, which contains an external link to a group in a second file, and that externally linked group contains items that are external links to a third file. If all the file paths are relative, the `nexusformat` package interprets the file path to the third file as relative to the parent file, not relative to the second file, and so can't locate the file.  

This should not occur if all the file paths are absolute, but there was a recently introduced bug that caused `abspath` to be improperly set when saving the file. When that is fixed, then all the links work correctly. 

I'll try to come up with a fix soon. I was nearly ready to issue another release of `nexusformat` but I'll make sure this is included. Although it seems like a tortuous example, it won't be that infrequent to have external links embedded in other externally linked files.

**Comment by rayosborn** [comment]
@TheGrim1, if you are able to install a development version, I have just merged changes into the master branch that should fix the bug you reported. If that's not possible, I can issue a release on Friday assuming the fix works.

**Comment by TheGrim1** [comment]
Hi Ray,

I installed the development version and unfortunately it does not solve the issue:

import nexusformat
nexusformat.__version__
> u'0.4.14+22.gb512873'

from nexusformat.nexus import *
mf1=nxload('/data/id13/inhouse2/AJ/skript/xsocs/my_example/test1.h5', 'w') mf1['entry']=NXentry() mf1['entry/data']=NXdata(NXfield(shape=(100,200,300), dtype=np.float32, name='data_0001')) mf2=nxload('/data/id13/inhouse2/AJ/skript/xsocs/my_example/test2.h5', 'w') mf2['entry']=NXentry() mf2['entry/data']=NXdata(NXfield(shape=(100,200,300), dtype=np.float32, name='data')) 
print(mf1.tree)

> root:NXroot
>   entry:NXentry
>     data:NXdata
>       @signal = 'data_0001'
>       data_0001 = float32(100x200x300)

link1f=nxload('/data/id13/inhouse2/AJ/skript/xsocs/my_example/link1.h5', 'w')
link1f['entry']=NXentry()
link1f['entry/data']=NXdata(name='data')
link1f['entry/data/data_0001']=NXlink('entry/data/data',file='/data/id13/inhouse2/AJ/skript/xsocs/my_example/test1.h5')
link1f['entry/data/data_0002']=NXlink('entry/data/data',file='/data/id13/inhouse2/AJ/skript/xsocs/my_example/test2.h5')

print(link1f.tree) 
> root:NXroot
>   entry:NXentry
>     data:NXdata
>       data_0001 -> /data/id13/inhouse2/AJ/skript/xsocs/my_example/test1.h5['entry/data/data']
>       data_0002 -> /data/id13/inhouse2/AJ/skript/xsocs/my_example/test2.h5['entry/data/data']

# BUT, now:

link1f['entry/data/data_0001'].shape

> AttributeError: Traceback (most recent call last) <ipython-input-12-b88268b917fd> in <module>()  ----> 2 link1f['entry/data/data_0001'].shape
> AttributeError: 'NXlink' object has no attribute 'shape'

# so this seems to be worse than before!

**Comment by rayosborn** [comment]
Thanks for looking into this so quickly. However, I think you didn't link to the correct path in link2f. Here are the relevant lines:
```
>>> mf1['entry/data']=NXdata(NXfield(shape=(100,200,300), dtype=np.float32, name='data_0001')) 
...
>>> link1f['entry/data/data_0001']=NXlink('entry/data/data',file='/data/id13/inhouse2/AJ/skript/xsocs/my_example/test1.h5')
```
The path in the original file, test1.h5, is `/entry/data/data_0001`, but you linked to `/entry/data/data`, which doesn't exist. That's why the shape lookup failed.

With the second file, test2.h5, you linked to the correct path, `/entry/data/data`.
```
mf2['entry/data']=NXdata(NXfield(shape=(100,200,300), dtype=np.float32, name='data'))
...
link1f['entry/data/data_0002']=NXlink('entry/data/data',file='/data/id13/inhouse2/AJ/skript/xsocs/my_example/test2.h5')
```
 I am guessing that `link2f['ext_link/data_0002'].shape` would have worked.

**Comment by TheGrim1** [comment]
Indeed, my bad on the typo, this version fixes my issue thanks!

**Comment by rayosborn** [comment]
Great. I will issue a release asap.
